# base image
FROM flink:1.19-scala_2.12-java11

# Create the user library directory Flink actually uses
RUN mkdir -p /opt/flink/usrlib

# Download 1.19-compatible connectors into usrlib
RUN wget -P /opt/flink/usrlib/ \
    https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.2.0-1.19/flink-sql-connector-kafka-3.2.0-1.19.jar && \
    wget -P /opt/flink/usrlib/ \
    https://repo1.maven.org/maven2/org/apache/flink/flink-json/1.19.0/flink-json-1.19.0.jar